# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# PER-DEPLOY.

# A redirect rule for single page apps such as mine
[[redirects]]
  from = "/*"
  to = "/index.html"

  # This will always redirect to index.html
  status = 200